### PR TITLE
[APPLICATION] Clawbird CHAOS

### PR DESCRIPTION
**Pull request by ltfschoen**
Project Abstract
> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).

**Application Checklist**

[X] The [application template](https://github.com/PolkadotPlay/GamesBounty/blob/main/applications/application-template.md) or [delivery template](https://github.com/PolkadotPlay/GamesBounty/blob/main/deliveries/delivery-template.md) has been copied and aptly renamed for an application (`project_name.md`) and a delivery (`project_name_m1.md`).
[X] I have read the [games bounty guidelines](https://github.com/PolkadotPlay/GamesBounty/blob/main/docs/gamesbounty_guidelines.md).
[ ] Payment details have been provided (Polkadot address in the application).
[ ] The initial PR contains only one commit (squash and force-push if needed).

### CODE REVIEW

**Comment by darkfriend77** [comment]
@ltfschoen Thanks for the application.

Could you check the formatting in the application on the 1. milestones?

**Comment by ltfschoen** [comment]
> @ltfschoen Thanks for the application.
> 
> Could you check the formatting in the application on the 1. milestones?

yes i've pushed a fix

**Comment by ltfschoen** [comment]
i have to prepare to help run a a Polkadot hackathon later this month at Consensus so i will have to put continuing this application on-hold until next month

**Comment by darkfriend77** [comment]
> i have to prepare to help run a a Polkadot hackathon later this month at Consensus so i will have to put continuing this application on-hold until next month

Okay. Just let us know when we shall start reviewing, until then good luck with your preparations for the Hackathon.

**Comment by ltfschoen** [comment]
> > i have to prepare to help run a a Polkadot hackathon later this month at Consensus so i will have to put continuing this application on-hold until next month
> 
> Okay. Just let us know when we shall start reviewing, until then good luck with your preparations for the Hackathon.

i'm going to have to close this application at the moment unfortunately. i'll have to revive it in future or pivot to something different. i was fortunate enough to unexpectedly recently get delegated voting power from W3F in Decentralized Voices program so that's going to take all my bandwidth over the next few months.

**Pull request closed without merging**
