### PR TITLE
Boorich/application game dev experience

### PR DESCRIPTION
**Pull request by boorich**
Project Abstract
> Please replace these instructions with a brief description of your project summarising key points (1-2 paragraphs).

**Application Checklist**

[ ] The [application template](https://github.com/PolkadotPlay/GamesBounty/blob/main/applications/application-template.md) or [delivery template](https://github.com/PolkadotPlay/GamesBounty/blob/main/deliveries/delivery-template.md) has been copied and aptly renamed for an application (`project_name.md`) and a delivery (`project_name_m1.md`).
[ ] I have read the [games bounty guidelines](https://github.com/PolkadotPlay/GamesBounty/blob/main/docs/gamesbounty_guidelines.md).
[ ] Payment details have been provided (Polkadot address in the application).
[ ] The initial PR contains only one commit (squash and force-push if needed).

### CODE REVIEW

**Comment by darkfriend77** [comment]
@boorich Thanks for the application. The GamesBounty team is reviewing it.

**Comment by carloskiron** [comment]
@darkfriend77 just flagging that we are still adding details but we expect to have a final version ready for review by this Friday May 10/2014. At the moment it's still a work in progress, it needs some additional color and internal revision to have it officially submitted your way.

**Comment by boorich** [comment]
@darkfriend77 This is still WIP. Please provide feedback and be in touch if you require further details. The team is working on this as we speak and we will see more commits.

**Comment by darkfriend77** [comment]
> @darkfriend77 just flagging that we are still adding details but we expect to have a final version ready for review by this Friday May 10/2014. At the moment it's still a work in progress, it needs some additional color and internal revision to have it officially submitted your way.

Okay, then we will wait till, you give us a go.

**Comment by TychoMasius** [comment]
In the final version, please also add any relationships the team might have with curators.

**Comment by driemworks** [comment]
replaced with: https://github.com/PolkadotPlay/GamesBounty/pull/8

**Pull request closed without merging**
